remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Λογος
description: I'm thinkin bout stuff
author: Luke Walker
url: https://kettlecornwitha-QU.github.io
nav:
  - home: /
  - posts: /_posts
  - birkhoff_and_schwarzschild: /birkhoff_and_schwarzschild
links:
  - title: Posts
    url: /_posts/
  - title: Birkhoff and Schwarzschild
    url: /birkhoff_and_schwarzschild
